title: SCsupercraft's Maven
description: Hosted Maven artifacts for SCsupercraft's projects.
baseurl: ''
url: 'https://maven.scsupercraft.dev'
theme: null
exclude:
    - .git
    - .github
    - .gitignore
    - package.json
    - package-lock.json
    - node_modules
    - scripts
    - README.md
