title: SCsupercraft's Maven
description: Hosted Maven artifacts for SCsupercraft's projects.
baseurl: ''
url: 'https://maven.scsupercraft.dev'
theme: null
exclude:
    - scripts
    - README.md

minima:
    nav_pages:
