{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.scsupercraft.teamstages",
    "module": "teamstages-1.20.1",
    "version": "1.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "teamstages-1.20.1-1.2.0.jar",
          "url": "teamstages-1.20.1-1.2.0.jar",
          "size": 63450,
          "sha512": "8c2fa89a94b91e4ce34fdbc267dedba57b6c2a3634f04e83357385c3a1499f3916183d8745f09d8a33088a58f70f13710e23da35113615eef779d9a2177ef05b",
          "sha256": "bd504217f57c9ebe99f85d15031e2d245e1c5192f3174b64110ce5cc99311f98",
          "sha1": "73678d5f415d93ecfbaf76698c303ce2e9d6ff4d",
          "md5": "de51dbe2705d1cdd97f3ae804e9b2e2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "dev.architectury",
          "module": "architectury-forge",
          "version": {
            "strictly": "9.2.14_mapped_parchment_2023.09.03-1.20.1",
            "requires": "9.2.14_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "net.darkhax.gamestages",
          "module": "GameStages-Forge-1.20.1",
          "version": {
            "strictly": "15.0.2_mapped_parchment_2023.09.03-1.20.1",
            "requires": "15.0.2_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "ftb-library-forge-404465",
          "version": {
            "strictly": "6807424_mapped_parchment_2023.09.03-1.20.1",
            "requires": "6807424_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "ftb-teams-forge-404468",
          "version": {
            "strictly": "6130786_mapped_parchment_2023.09.03-1.20.1",
            "requires": "6130786_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "curse.maven",
          "module": "ftb-quests-forge-289412",
          "version": {
            "strictly": "7260736_mapped_parchment_2023.09.03-1.20.1",
            "requires": "7260736_mapped_parchment_2023.09.03-1.20.1"
          }
        },
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.3.25_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "teamstages-1.20.1-1.2.0.jar",
          "url": "teamstages-1.20.1-1.2.0.jar",
          "size": 63450,
          "sha512": "8c2fa89a94b91e4ce34fdbc267dedba57b6c2a3634f04e83357385c3a1499f3916183d8745f09d8a33088a58f70f13710e23da35113615eef779d9a2177ef05b",
          "sha256": "bd504217f57c9ebe99f85d15031e2d245e1c5192f3174b64110ce5cc99311f98",
          "sha1": "73678d5f415d93ecfbaf76698c303ce2e9d6ff4d",
          "md5": "de51dbe2705d1cdd97f3ae804e9b2e2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teamstages-1.20.1-1.2.0-sources.jar",
          "url": "teamstages-1.20.1-1.2.0-sources.jar",
          "size": 32077,
          "sha512": "ba81eeee8c6e36f2cbb14a8794ff50b3fcb84f0950903aebd0fa7d5524f56961c8ed29d04079aecc20892a6062cb04493b1148d7b778d9770176e1f399bd063f",
          "sha256": "28da3c094099bf04d406e48381fb7e43ca9b96912f72da00901b63d660e5a1bd",
          "sha1": "6214585b1fc1341d8b4475aa01ae6b1365ba291f",
          "md5": "aebe09be00c6653d09f5926a68c9ecec"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "teamstages-1.20.1-1.2.0-javadoc.jar",
          "url": "teamstages-1.20.1-1.2.0-javadoc.jar",
          "size": 122936,
          "sha512": "a5d0cf80a395248831069983d934131d132dc1c7c304cb4579977845e7c182cebe8fa9ed3849e3553021c15765a04f6fed3e95d72138c911284733772a0a066d",
          "sha256": "5be053671104739ae37ad6169e5a71731699787c46d81675c07b4fd8a6a9a850",
          "sha1": "26ddf77105a85c7f3723a8a2476f78e097169d55",
          "md5": "dcd4f5752dc1d7513a70690d814fead2"
        }
      ]
    }
  ]
}
